# Site settings
title: a blog.
description: >
  A blog about learning.
baseurl: ""
url: "https://blog.loganmcdonald.dev"
twitter_username: _loganmcdonald
github_username:  loganmeetsworld

# Build settings
markdown: kramdown
theme: jekyll-theme-tactile
