# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Logan Meets World
email: loganmcdona11@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog where I talk about things I learn.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://loganmeetsworld.com" # the base hostname & protocol for your site
twitter_username: loganmeetsworld
github_username:  loganmeetsworld

# Build settings
markdown: kramdown
